name: Run Tests
on:
  push:
  workflow_dispatch:

jobs:
  doit:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: MikeSchulze/gdUnit4-action@v1.1.1
        name: Run tests
        with:
          godot-version: '4.3'
          godot-status: 'stable'
          paths: 'res://test'
          version: 'installed'
          arguments: '-i download_request_integration_test'
