name: Run Tests
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  doit:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 20

      - uses: MikeSchulze/gdUnit4-action@v1
        name: Run tests
        with:
          godot-version: '4.3'
          godot-status: 'stable'
          paths: 'res://tests'
